import { chromium, expect } from '@playwright/test';
import { mkdirSync, readFileSync } from 'node:fs';
const browser = await chromium.launch();
const directory = 'artifacts/screenshots'; mkdirSync(directory, { recursive: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const pageErrors: string[] = []; page.on('pageerror', error => pageErrors.push(error.message));
await page.addInitScript({ content: `
  const original = crypto.getRandomValues.bind(crypto);
  Object.defineProperty(crypto, 'getRandomValues', { configurable: true, value: (array) => {
    if (array instanceof Uint32Array && array.length === 1) { array[0] = 2; return array; }
    return original(array);
  } });
` });
await page.goto('http://127.0.0.1:4322/');
await page.getByRole('button', { name: 'Pick a player' }).waitFor();
await page.screenshot({ path: `${directory}/desktop-ready.png`, fullPage: true });
await page.getByRole('button', { name: 'Pick a player' }).click();
await page.locator('.picker[data-phase=result]').waitFor();
await expect(page.locator('.winner-announcement')).toContainText('Seat 3 goes first.');
await page.screenshot({ path: `${directory}/desktop-result.png`, fullPage: true });
await page.setViewportSize({ width: 390, height: 844 }); await page.reload();
await page.getByRole('button', { name: 'Pick a player' }).waitFor();
await page.screenshot({ path: `${directory}/mobile-ready.png`, fullPage: true });
await page.getByRole('link', { name: 'How it works', exact: true }).click();
await page.screenshot({ path: `${directory}/mobile-help.png`, fullPage: true });
await page.goto('http://127.0.0.1:4322/');
await page.getByRole('button', { name: 'Paste a list' }).click();
await page.getByLabel('Player names').fill('Mina\n王芳\nAlex\nAlex');
await page.getByRole('button', { name: 'Pick a player' }).click(); await page.locator('.picker[data-phase=result]').waitFor();
await expect(page.locator('.winner-announcement')).toContainText('Alex · #3 goes first.');
await page.screenshot({ path: `${directory}/mobile-named-result.png`, fullPage: true });
await page.getByLabel('Player names').fill('One player');
await page.screenshot({ path: `${directory}/mobile-invalid-input.png`, fullPage: true });
await page.goto('http://127.0.0.1:4322/games/');
await page.getByRole('searchbox').fill('Unlisted game');
await page.screenshot({ path: `${directory}/mobile-empty-search.png`, fullPage: true });
await page.goto('http://127.0.0.1:4321/dev/rules/azul-2018-en/');
await page.screenshot({ path: `${directory}/mobile-draft-rule.png`, fullPage: true });
await page.setViewportSize({ width: 1440, height: 1000 });
await page.goto('http://127.0.0.1:4321/dev/review/');
await page.screenshot({ path: `${directory}/desktop-review-queue.png`, fullPage: true });
await page.goto('http://127.0.0.1:4322/methods/balloon/');
await page.getByLabel('Player count').selectOption('12');
await page.getByRole('button', { name: 'Pick a player' }).click();
await page.locator('.balloon-field').waitFor();
// Set all CSS animation timelines to a known point, then pause them.
await page.evaluate(() => document.getAnimations().forEach(animation => { animation.pause(); animation.currentTime = 900; }));
await page.screenshot({ path: `${directory}/desktop-balloon-controlled.png`, fullPage: true });
await page.getByRole('button', { name: 'Show result now' }).click();
await page.screenshot({ path: `${directory}/desktop-balloon-result.png`, fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole('button', { name: 'Paste a list' }).click();
await page.getByLabel('Player names').fill(Array.from({ length: 12 }, (_, i) => `LongName${i}abcdefghijklmn`).join('\n'));
await page.getByRole('button', { name: 'Done', exact: true }).click();
await page.getByRole('button', { name: 'Pick a player' }).click(); await page.locator('.balloon-field').waitFor();
await page.evaluate(() => document.getAnimations().forEach(animation => { animation.pause(); animation.currentTime = 900; }));
await page.screenshot({ path: `${directory}/mobile-balloon-long-names.png`, fullPage: true });
await page.setViewportSize({ width: 320, height: 740 });
await page.goto('http://127.0.0.1:4322/');
await expect(page.getByRole('button', { name: 'Pick a player' })).toBeEnabled();
await page.screenshot({ path: `${directory}/reflow-320.png`, fullPage: true });
await page.setViewportSize({ width: 1366, height: 768 }); await page.goto('http://127.0.0.1:4322/');
const action = await page.getByRole('button', { name: 'Pick a player' }).boundingBox();
expect(action!.y + action!.height).toBeLessThan(768);
await page.screenshot({ path: `${directory}/laptop-ready.png`, fullPage: true });
await page.screenshot({ path: `${directory}/desktop-viewport.png` });
await page.getByRole('button', { name: 'Preferences' }).click();
await page.screenshot({ path: `${directory}/desktop-preferences.png`, fullPage: true });
await page.goto('http://127.0.0.1:4322/');
await page.evaluate("Object.defineProperty(crypto, 'getRandomValues', { value: () => { throw new Error('Test-only blocked RNG'); } });");
await page.getByRole('button', { name: 'Pick a player' }).click();
await expect(page.getByRole('alert')).toContainText('No player was selected');
await page.screenshot({ path: `${directory}/desktop-rng-failure.png`, fullPage: true });
await page.goto('http://127.0.0.1:4322/about/');
await page.screenshot({ path: `${directory}/desktop-about.png`, fullPage: true });
expect(pageErrors).toEqual([]);
await page.setViewportSize({ width: 1200, height: 630 });
await page.setContent(readFileSync('public/social.svg', 'utf8')); await page.evaluate(() => { document.body.style.margin = '0'; });
await page.screenshot({ path: 'public/social.png' });
await browser.close();
console.log(`Captured 18 review screenshots in ${directory}; deterministic winners asserted; no unexpected page errors; social.png rendered from original SVG.`);
