import { chromium, expect } from '@playwright/test';
import { mkdirSync, readdirSync } from 'node:fs';

const browser = await chromium.launch();
const directory = 'artifacts/screenshots';
mkdirSync(directory, { recursive: true });
const failures: string[] = [];
try {
  const page = await browser.newPage({ viewport: { width: 1366, height: 768 } });
  page.on('pageerror', error => failures.push(error.message));
  page.on('console', message => { if (message.type() === 'error') failures.push(message.text()); });
  page.on('response', response => { if (response.status() >= 400) failures.push(`${response.status()} ${response.url()}`); });
  await page.goto('http://127.0.0.1:4321/');
  await expect(page.getByRole('button', { name: 'Pick a player' })).toBeEnabled();
  const desktopAction = await page.getByRole('button', { name: 'Pick a player' }).boundingBox();
  expect(desktopAction!.y + desktopAction!.height).toBeLessThan(768);
  await page.screenshot({ path: `${directory}/dev-desktop-ready.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  const mobileAction = await page.getByRole('button', { name: 'Pick a player' }).boundingBox();
  expect(mobileAction!.y + mobileAction!.height).toBeLessThan(844);
  await page.screenshot({ path: `${directory}/dev-mobile-ready.png`, fullPage: true });
  await page.getByRole('button', { name: 'Paste a list' }).click();
  await page.getByLabel('Player names').fill('Mina\nAlex\nJo');
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.getByRole('radio', { name: /^Balloon Rise/ }).check();
  await page.getByRole('button', { name: 'Pick a player' }).click();
  await expect(page.locator('.winner-announcement')).toContainText(/(Mina|Alex|Jo) goes first/);
  await page.screenshot({ path: `${directory}/dev-mobile-result.png`, fullPage: true });
  await page.getByRole('link', { name: 'Game rules', exact: true }).click();
  const count = readdirSync('research/games').filter(name => name.endsWith('.json')).length;
  await expect(page.locator('.game-list li')).toHaveCount(count);
  await page.getByRole('button', { name: 'Pick a rule' }).click();
  await expect(page.locator('[data-rule-answer]')).not.toBeEmpty();
  await page.setViewportSize({ width: 1366, height: 1000 });
  await page.screenshot({ path: `${directory}/dev-game-directory.png`, fullPage: true });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `${directory}/dev-game-directory-overview.png` });
  await page.getByRole('searchbox').fill('Spin Circus');
  await expect(page.locator('.game-list li:visible')).toHaveCount(2);
  await page.screenshot({ path: `${directory}/dev-editions-desktop.png`, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('link', { name: /Spin Circus UK English/ }).click();
  await expect(page.locator('.rule-answer')).toContainText('stage');
  await page.screenshot({ path: `${directory}/dev-edition-mobile.png`, fullPage: true });
  await page.goto('http://127.0.0.1:4321/dev/games/');
  await page.getByRole('searchbox').fill('uno');
  await page.locator('.game-list li:visible a').click();
  await expect(page.locator('.rule-answer')).toContainText('dealer');
  await page.screenshot({ path: `${directory}/dev-mobile-uno.png`, fullPage: true });
  await page.goto('http://127.0.0.1:4321/dev/rules/7-wonders-2020-en/');
  await expect(page.locator('.rule-answer')).toContainText('no single starting player');
  await page.screenshot({ path: `${directory}/dev-mobile-simultaneous.png`, fullPage: true });
  await page.goto('http://127.0.0.1:4321/dev/house-rules/');
  const previous = await page.locator('[data-prompt]').textContent();
  await page.getByRole('button', { name: 'Skip', exact: true }).click();
  await expect(page.locator('[data-prompt]')).not.toHaveText(previous!);
  await page.screenshot({ path: `${directory}/dev-house-rules.png`, fullPage: true });
  await page.goto('http://127.0.0.1:4321/dev/coverage/');
  await page.setViewportSize({ width: 1366, height: 900 });
  await expect(page.getByRole('searchbox')).toBeEnabled();
  await page.screenshot({ path: `${directory}/dev-coverage-desktop.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('searchbox').fill('265736');
  await expect(page.locator('.coverage-list li:visible')).toHaveCount(1);
  await page.screenshot({ path: `${directory}/dev-coverage-mobile.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(failures).toEqual([]);
  console.log(`Captured twelve live-development screenshots; picks, navigation, ${count}-rule directory, distinct editions, random rule, full discovery search, source answers, prompt skip and above-fold actions verified; no page, console or HTTP errors.`);
} finally { await browser.close(); }
