import { writeFileSync } from 'node:fs';
import { getCatalog } from '../src/lib/content/catalog';
import { publisherHubs } from '../src/lib/content/hubs';

// Writes marketing/PUBLISHER_OUTREACH.md: one ready-to-send email per publisher hub,
// largest first. Drafts only; the owner finds the contact address and sends them.
const origin = 'https://whogoesfirst.fun';
const hubs = publisherHubs(getCatalog()).sort((a, b) => b.rules.length - a.rules.length || a.name.localeCompare(b.name));
const sections = hubs.map(hub => {
  const sample = [...hub.rules].sort((a, b) => a.gameName.localeCompare(b.gameName)).slice(0, 3);
  const list = sample.map(rule => `- ${rule.gameName}: ${origin}/games/${rule.slug}/`).join('\n');
  return `## ${hub.name} (${hub.rules.length} rules)

**Subject:** We cite your rulebooks: ${hub.rules.length} ${hub.name} starting-player answers

Hi ${hub.name} team,

I run Who Goes First? (${origin}), a free site that answers one question players search for at the table: who starts? Each answer names the edition it applies to and links to your official rulebook as the source.

We currently cover ${hub.rules.length} of your games, collected here: ${origin}/publishers/${hub.slug}/

For example:
${list}

Two small requests, only if they're useful to you:
1. If any answer doesn't match your current edition, reply with the rulebook page and I'll correct it.
2. If you have a rules-download, FAQ or support page, a link to your collection page could save your players a search. There's also a free copy-and-paste embed: ${origin}/embed/

Thanks for making games worth arguing about who goes first in.

Best,
[Your name]
Who Goes First?
`;
});
writeFileSync('marketing/PUBLISHER_OUTREACH.md', `# Publisher outreach drafts

Generated by \`npx tsx scripts/outreach-drafts.ts\` from ${hubs.length} publisher pages, largest first. **Drafts only; nothing has been sent.**

How to use: find each publisher's press, community or support address on their own site (not a sales form), personalise the first line, and send a few a day rather than all at once. Log replies and any links earned in \`GROWTH_STATUS.md\`. Skip publishers whose site asks for no unsolicited email.

${sections.join('\n---\n\n')}`);
console.log(`Wrote ${hubs.length} drafts.`);
