import { writeFileSync } from 'node:fs';
import { getCatalog } from '../src/lib/content/catalog';
import { publisherHubs } from '../src/lib/content/hubs';

// Writes marketing/PUBLISHER_OUTREACH.md: one ready-to-send email per publisher hub,
// largest first. Drafts only; actual delivery belongs in the separate send log.
const origin = 'https://whogoesfirst.fun';
const hubs = publisherHubs(getCatalog()).sort((a, b) => b.rules.length - a.rules.length || a.name.localeCompare(b.name));
const sections = hubs.map(hub => {
  const sample = [...hub.rules].sort((a, b) => a.gameName.localeCompare(b.gameName)).slice(0, 3);
  const list = sample.map(rule => `- ${rule.gameName}: ${origin}/games/${rule.slug}/`).join('\n');
  return `## ${hub.name} (${hub.rules.length} rules)

**Subject:** We cite your rulebooks: ${hub.rules.length} ${hub.name} starting-player answers

Hi ${hub.name} team,

I run Who Goes First? (${origin}), a free site that answers one question players search for at the table: who starts? Each answer names the edition it applies to and links to your official rulebook as the source.

We currently cover ${hub.rules.length} of your games, collected here: ${origin}/publishers/${hub.slug}/

For example:
${list}

Two small requests, only if they're useful to you:
1. If any answer doesn't match your current edition, reply with the rulebook page and I'll correct it.
2. If you have a rules-download, FAQ or support page, a link to your collection page could save your players a search. There's also a free copy-and-paste embed: ${origin}/embed/

Thanks for making games worth arguing about who goes first in.

Best,
[Your name]
Who Goes First?
`;
});
writeFileSync('marketing/PUBLISHER_OUTREACH.md', `# Publisher outreach drafts

Generated by \`npx tsx scripts/outreach-drafts.ts\` from ${hubs.length} publisher pages, largest first. **Draft snapshots only; this generator does not send messages.** Consult [OUTREACH_LOG.md](OUTREACH_LOG.md) for actual delivery history.

Recheck counts, editions, source links and each preferred contact route against the live site before use. Personalized research is in [VERIFIED_OUTREACH.md](VERIFIED_OUTREACH.md); current channel operations are in [AUTOMATION.md](AUTOMATION.md). Never resend to a contacted publisher unless it replied requesting something.

How to use: prefer a publisher's current press/community route on its own site and personalize around one verified edition. Reserve customer support for appropriate support or rule-correction requests. Follow the existing routine only within current authorization; record actual sends, replies and earned links in [OUTREACH_LOG.md](OUTREACH_LOG.md). Skip recipients that reject unsolicited email or request a different route.

${sections.join('\n---\n\n')}`);
console.log(`Wrote ${hubs.length} drafts.`);
